class NewsService(Protocol):
    def ingest(self, articles: list[Article]) -> None: ...

    def list_feed(
        self,
        limit: int = 100,
        unread_only: bool = False,
    ) -> list["ArticleView"]: ...

    def vote(self, article_url: str, vote: str) -> None: ...

    def mark_read(self, article_url: str) -> None: ...

    def save(self, article_url: str, saved: bool) -> None: ...

    def archive(self, article_url: str, archived: bool) -> None: ...
